// <auto-generated />
using System;
using Mamao.People.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mamao.People.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    [Migration("20260815010416_SetorSemDuplicata")]
    partial class SetorSemDuplicata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mamao.People.Domain.Availability.AbsenceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("decided_by_name");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_note");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_absence_requests");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_absence_requests_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId", "StartsOn")
                        .HasDatabaseName("ix_absence_requests_tenant_id_employee_id_starts_on");

                    b.HasIndex("TenantId", "Status", "StartsOn")
                        .HasDatabaseName("ix_absence_requests_tenant_id_status_starts_on");

                    b.ToTable("absence_requests", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Availability.Occupancy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_occupancies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_occupancies_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId", "StartsOn")
                        .HasDatabaseName("ix_occupancies_tenant_id_employee_id_starts_on");

                    b.HasIndex("TenantId", "Source", "SourceId")
                        .HasDatabaseName("ix_occupancies_tenant_id_source_source_id");

                    b.HasIndex("TenantId", "StartsOn", "EndsOn")
                        .HasDatabaseName("ix_occupancies_tenant_id_starts_on_ends_on");

                    b.ToTable("occupancies", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateOnly>("HiredOn")
                        .HasColumnType("date")
                        .HasColumnName("hired_on");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly?>("TerminatedOn")
                        .HasColumnType("date")
                        .HasColumnName("terminated_on");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_employees");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employees_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("TenantId", "DepartmentId")
                        .HasDatabaseName("ix_employees_tenant_id_department_id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_tenant_id_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("TenantId", "FullName")
                        .HasDatabaseName("ix_employees_tenant_id_full_name");

                    b.HasIndex("TenantId", "ManagerId")
                        .HasDatabaseName("ix_employees_tenant_id_manager_id");

                    b.HasIndex("TenantId", "PositionId")
                        .HasDatabaseName("ix_employees_tenant_id_position_id");

                    b.ToTable("employees", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.EmployeeRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("activity_key");

                    b.Property<string>("ActivityName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("activity_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_employee_restrictions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employee_restrictions_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .HasDatabaseName("ix_employee_restrictions_tenant_id_employee_id");

                    b.HasIndex("TenantId", "StartsOn")
                        .HasDatabaseName("ix_employee_restrictions_tenant_id_starts_on");

                    b.ToTable("employee_restrictions", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.EmploymentContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CompensationAgreementOn")
                        .HasColumnType("date")
                        .HasColumnName("compensation_agreement_on");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Regime")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("regime");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("schedule_type");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("WeeklyHours")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("weekly_hours");

                    b.HasKey("Id")
                        .HasName("pk_employment_contracts");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_employment_contracts_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_employment_contracts_tenant_id_employee_id");

                    b.ToTable("employment_contracts", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Missions.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("On")
                        .HasColumnType("date")
                        .HasColumnName("on");

                    b.Property<int>("RequiredPeople")
                        .HasColumnType("integer")
                        .HasColumnName("required_people");

                    b.Property<TimeOnly?>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_missions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_missions_tenant_id");

                    b.HasIndex("TenantId", "On")
                        .HasDatabaseName("ix_missions_tenant_id_on");

                    b.ToTable("missions", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Missions.MissionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mission_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_mission_assignments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mission_assignments_tenant_id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .HasDatabaseName("ix_mission_assignments_tenant_id_employee_id");

                    b.HasIndex("TenantId", "MissionId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ix_mission_assignments_tenant_id_mission_id_employee_id");

                    b.ToTable("mission_assignments", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Missions.RotationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("MinRestDays")
                        .HasColumnType("integer")
                        .HasColumnName("min_rest_days");

                    b.Property<bool>("RestBlocks")
                        .HasColumnType("boolean")
                        .HasColumnName("rest_blocks");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tiebreak")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tiebreak");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("window_days");

                    b.HasKey("Id")
                        .HasName("pk_rotation_policies");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_rotation_policies_tenant_id");

                    b.ToTable("rotation_policies", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Organization.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("path");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_departments_tenant_id");

                    b.HasIndex("TenantId", "Path")
                        .HasDatabaseName("ix_departments_tenant_id_path");

                    b.HasIndex("TenantId", "ParentId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_tenant_id_parent_id_normalized_name");

                    b.ToTable("departments", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Organization.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<int?>("PrecedenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("precedence_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_positions_tenant_id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_positions_tenant_id_normalized_name");

                    b.ToTable("positions", "people");
                });

            modelBuilder.Entity("Mamao.People.Domain.Work.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_name");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_work_items");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_items_tenant_id");

                    b.HasIndex("TenantId", "AssigneeId", "Status")
                        .HasDatabaseName("ix_work_items_tenant_id_assignee_id_status");

                    b.HasIndex("TenantId", "DepartmentId", "Status")
                        .HasDatabaseName("ix_work_items_tenant_id_department_id_status");

                    b.HasIndex("TenantId", "Status", "DueOn")
                        .HasDatabaseName("ix_work_items_tenant_id_status_due_on");

                    b.ToTable("work_items", "people");
                });

            modelBuilder.Entity("Mamao.SharedKernel.Auditing.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("ActorIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("actor_ip");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectLabel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject_label");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("TenantId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_entries_tenant_id_occurred_at");

                    b.HasIndex("TenantId", "SubjectType", "SubjectId")
                        .HasDatabaseName("ix_entries_tenant_id_subject_type_subject_id");

                    b.ToTable("entries", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Mamao.SharedKernel.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Mamao.People.Domain.Availability.AbsenceRequest", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_absence_requests_employees_employee_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Availability.Occupancy", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_occupancies_employees_employee_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.Employee", b =>
                {
                    b.HasOne("Mamao.People.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_departments_department_id");

                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_employees_employees_manager_id");

                    b.HasOne("Mamao.People.Domain.Organization.Position", null)
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_employees_positions_position_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.EmployeeRestriction", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employee_restrictions_employees_employee_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Employees.EmploymentContract", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_employment_contracts_employees_employee_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Missions.MissionAssignment", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_assignments_employees_employee_id");

                    b.HasOne("Mamao.People.Domain.Missions.Mission", null)
                        .WithMany("Assignments")
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mission_assignments_missions_mission_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Organization.Department", b =>
                {
                    b.HasOne("Mamao.People.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_departments_departments_parent_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Work.WorkItem", b =>
                {
                    b.HasOne("Mamao.People.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_items_employees_assignee_id");

                    b.HasOne("Mamao.People.Domain.Organization.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_items_departments_department_id");
                });

            modelBuilder.Entity("Mamao.People.Domain.Missions.Mission", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
